Repository DUNE-DAQ/trgdataformats, pull requests merged in 2024-03, with the labels that each got.

#14 New DBSCAN TCMaker
  include/trgdataformats/TriggerCandidateData.hpp
  pybindsrc/trigger_candidate.cpp
Labels: maintenance, miscellaneous deliverable

#12 New ChannelDistance Algorithm
  include/trgdataformats/TriggerActivityData.hpp
  include/trgdataformats/TriggerCandidateData.hpp
  pybindsrc/trigger_activity.cpp
  pybindsrc/trigger_candidate.cpp
Labels: enhancement, miscellaneous deliverable

#15 New BundleN Algorithm & Type
  include/trgdataformats/TriggerActivityData.hpp
  include/trgdataformats/TriggerCandidateData.hpp
  pybindsrc/trigger_activity.cpp
  pybindsrc/trigger_candidate.cpp
Labels: maintenance, miscellaneous deliverable

#16 CTB: Trigger integration
  include/trgdataformats/TriggerCandidateData.hpp
  pybindsrc/trigger_candidate.cpp
Labels: miscellaneous deliverable

#13 Asztuc/trigger neutron source
  include/trgdataformats/TriggerCandidateData.hpp
  pybindsrc/trigger_candidate.cpp
Labels: miscellaneous deliverable

#18 new ChannelAdjacency algorithm
  include/trgdataformats/TriggerActivityData.hpp
  include/trgdataformats/TriggerCandidateData.hpp
  pybindsrc/trigger_activity.cpp
  pybindsrc/trigger_candidate.cpp
Labels: miscellaneous deliverable
